  name: Example workflow


  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
    workflow_dispatch:

  jobs:
    example:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: example 
          run: echo "this is an example"
          shell: bash

     goodbye:
       runs-on: ubuntu-latest
       steps:
         - name: goodbye world
           run: echo "goodbye"
           shell: bash
        
